Feature/ff butter
popcorndao/sweet-caramel pull request #299
Opened 2022-01-19 17:17 UTC by RedVeil

2022-04-30 16:50 UTC, anthonymartin commented
@RedVeil could you bring this PR up to speed with develop ? and any thoughts on connor's comments?

2022-05-16 17:46 UTC, RedVeil commented on packages/hardhat/contracts/mocks/MockCurveFactory2Metapool.sol
> +}
i think its good enough for this since we have additional integration tests but we certainly pushed them to their limit in its current form

2022-05-16 18:29 UTC, anthonymartin requested changes
looks good - the batch contract needs a bit of refactor on the batchMint side so it's as clean as the butter batch contract.

can we add minting & swap fees too to this?

2022-05-16 18:29 UTC, anthonymartin commented on packages/hardhat/contracts/core/defi/butter/FourXBatchProcessing.sol
> +  function batchMint() external whenNotPaused keeperIncentive(contractName, 0) {
this function should be refactored so it looks more like the ButterBatch one

2022-06-14 10:19 UTC, closed without merging