Added reverse lookup mapping to contractRegistry and a view function to retrieve it
popcorndao/sweet-caramel pull request #457
Opened 2022-02-16 10:26 UTC by bhanusanghi

Add the relevant lookup mapping,  view function to retrieve it and tests to existing test suite to make sure all things work perfectly and bug free

2022-03-21 14:39 UTC, anthonymartin requested changes

2022-03-21 14:43 UTC, anthonymartin commented on packages/hardhat/contracts/core/utils/ContractRegistry.sol
> +  function getContractFromAddress(address _contractAddress) external view override returns (bytes32) {
shouldn't this say getContractNameFromAddress ?

2022-04-05 15:20 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/ContractRegistry.sol
> +  function getContractFromAddress(address _contractAddress) external view override returns (bytes32) {
Or perhaps `getContractIdFromAddress`, since these are keccak hashes of the name + id.

2022-05-18 15:04 UTC, RedVeil approved these changes

2022-05-18 15:06 UTC, merged