Feature/btrv2 integration
popcorndao/sweet-caramel pull request #554
Opened 2022-03-21 15:27 UTC by RedVeil

Tested Integration of BTR-V2. Frontend works as expected. Added minor display improvements.

 -- One caviat of the hooks is that the butterBatchData reloads everytime an on chain interaction has happened. Everytime this happens this Mint/Redeem Interface will switch back to the default view of minting BTR with 3CRV. This means that if a user approves BTR or USDC for example they will need to go back to their tab/ currency from the default view. But since we need this useEffect to display everything correctly on inital load im not sure how to change this.
  -> I would keep this in mind and currently roll with it. If we find a better way in the future we should certainly change this.
  
  -- When minting BTR their is only on the first time a modal guiding you what to do. On redeem their is a modal that pops up everytime. Since we dont really have a way of knowing if a user minted BTR before i think we should just show the modal for redemption also only once.

2022-03-21 15:29 UTC, RedVeil commented
Ticket https://github.com/popcorndao/sweet-caramel/pull/554

2022-03-21 16:00 UTC, RedVeil commented
to my comments above:
- I added an initalLoad boolean which gets set when data gets loaded the first time. Only on initalLoad we set the input token to 3crv and ouput to butter in all other cases we simply utilize the MintRedeemToggle

- For the modals i changed the system to now have one mint and one redeem modal which always show if the user doesnt click "dont remind me again"

2022-03-22 11:12 UTC, RedVeil commented
- Est. APY shows now the yield from BTR + APY from butter staking.
- Added a Tooltip and extra line of text explaining how to get the full apy.
- Mint and redeem modal are now essentially the same and point the user to the table below to check their batches. They  can both be closed once or the user can choose to not be reminded again.
- SelectedToken uses keys now. Therefore we can update the data on each token while still remembering which token a user had selected after an onchain action.

2022-03-22 11:25 UTC, arne-z approved these changes

2022-03-22 11:46 UTC, anthonymartin requested changes

2022-03-22 11:46 UTC, anthonymartin commented on packages/app/pages/butter.tsx
> +                                    underlying token back into 3CRV or your desired stablecoin.
```suggestion
                                    underlying tokens back into 3CRV or your desired stablecoin.
```

2022-03-22 11:46 UTC, anthonymartin commented on packages/app/pages/butter.tsx
> +                                    Mint BTR with 3CRV or stablecoins to earn interest on multiple Stablecoins at once.
i like this copy change here

2022-03-22 11:46 UTC, anthonymartin commented on packages/app/components/BatchButter/MintRedeemToggle.tsx
> +              content="Mint BTR with 3CRV or stablecoins to earn interest on multiple Stablecoins at once."
Do you want to pull in the copy from below that I commented on here so this is more explanatory?

2022-03-22 11:55 UTC, RedVeil commented on packages/app/components/BatchButter/MintRedeemToggle.tsx
> +              content="Mint BTR with 3CRV or stablecoins to earn interest on multiple Stablecoins at once."
sry im a little confused which copy from where? Do you mean adding this back in: "The minting process involves converting deposited stablecoins into other stable assets that are compatible with the yield accrual strategy."

2022-03-22 17:14 UTC, anthonymartin approved these changes

2022-03-22 17:14 UTC, anthonymartin commented on packages/app/components/BatchButter/MintRedeemToggle.tsx
> +              them in Yearn to generate interest."
```suggestion
              them to automated yield-farming contracts by Yearn to generate interest."
```

2022-03-23 11:06 UTC, merged