Feature/beneficiary application step 3
popcorndao/sweet-caramel pull request #663
Opened 2022-05-02 12:43 UTC by Ajiva-D

2022-05-09 11:25 UTC, Ajiva-D commented
I removed the "upload files" button that is the design from the implementation cos it's not needed. When the file is selected from the input, it starts uploading to IPFS, we don't need another button to upload.

2022-05-17 11:32 UTC, arne-z requested changes

2022-05-17 11:32 UTC, arne-z commented on packages/grants/components/CommonComponents/IPFSUploadFunc.tsx
> +const isFailedUpload = (res: UploadResult): boolean => res.status !== 200;
It seems that UploadResult doesn't expose a .ok entry, otherwise I'd recommend using that here. Should we be concerned about 2xx results other than 200 occurring and falsely getting flagged as errors?

2022-05-17 11:32 UTC, arne-z commented on packages/grants/components/CommonComponents/IPFSUploadFunc.tsx
> +};
I'm not sure I fully understand this check.
The upload box is displayed if the local state is of string type and empty or if it is of array type and there is still "space" for more files to be uploaded right?
The second half of this makes sense but I'm not sure why the first check is the way it is.
This might be a good place to leave a comment explaining this.

2022-05-17 11:32 UTC, arne-z commented on packages/grants/components/CommonComponents/SocialMedia.tsx
> +        <SocialMediaIcon url={beneficiary?.links.contactEmail.data} platform={"email"} />
Are we certain beneficiary?.links.contactEmail will always be defined? This will throw a typeerror if it's trying to access .contactEmail of undefined, so it might be good to add more "?" here.
```suggestion
        <SocialMediaIcon url={beneficiary?.links?.contactEmail?.data} platform={"email"} />
```

2022-05-17 11:32 UTC, arne-z commented on packages/grants/components/Proposals/Form/Intro.tsx
> +                {formData.organizationName.data !== "" && (
I wonder if this should either be an explicit check for data to be defined and empty or a check for data to be truthy, as right now this will be true on undefined or defined and having content.

2022-05-17 11:32 UTC, arne-z commented on packages/grants/styles/globals.css
> +}
```suggestion
}

```

2022-05-17 11:50 UTC, Ajiva-D commented on packages/grants/components/Apply/CoverPhotoUpload.tsx
> +              {" "}
definitely formatting

2022-05-17 11:51 UTC, Ajiva-D commented on packages/grants/components/Apply/FlowSteps.tsx
> +  active: Number;
Steps are enum, this is a prop to pass the current step. The enum is declared in /pages//apply/form

2022-05-17 11:51 UTC, Ajiva-D commented on packages/grants/components/Apply/GeneralInformation.tsx
> +      {" "}
formatting

2022-05-30 17:19 UTC, arne-z approved these changes

2022-05-30 17:20 UTC, merged