Vault Zapper example
popcorndao/sweet-caramel pull request #711
Opened 2022-05-10 20:32 UTC by ecmendenhall

A POC vault zapper using the Zapper Curve zap contracts. See the annotated test case for all the details.

2022-05-24 22:18 UTC, anthonymartin commented on packages/hardhat/lib/tasks/curve/metapoolInterfaces.ts
> +export default task("curve:metapool-interfaces", "get all curve metapool interfaces and save them to a file")
nice

2022-05-24 22:18 UTC, anthonymartin commented on packages/hardhat/lib/tasks/forge/forgeTest.ts
> +export default task("forge:forge-test", "run forge tests")
this is cool. we can also use the `scripts` property in `package.json` to call scripts dynamically as well without having to write as much code

2022-06-09 12:48 UTC, anthonymartin approved these changes

2022-07-04 18:00 UTC, anthonymartin requested changes

2022-07-04 18:00 UTC, anthonymartin commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    IERC20(toToken).safeTransfer(_getContract(FEE_CONTROLLER_ID), amountOut);
https://github.com/popcorndao/sweet-caramel/blob/feature/vault-zapper-zerox/packages/hardhat/contracts/core/defi/vault/VaultFeeController.sol

There's nothing in this contract to transfer fees out. I think we should replace this with a treasury that's defined in this contract itself

2022-07-04 18:07 UTC, anthonymartin commented on packages/hardhat/lib/adapters/Zapper.ts
> +    const [coin0, coin1] = await this.getCoins(curveLPAddress, vault.provider);
https://curve.readthedocs.io/registry-registry.html#getting-info-about-a-pool

we could use the registry to `get_coins` which should work for all pools

2022-07-06 22:03 UTC, ecmendenhall commented
Fixed up the Forge test fork block here. 

The Forge tests are now wrapped in a `hardhat forge:forge-test` task that lets us specify different blocks per test file [here](https://github.com/popcorndao/sweet-caramel/blob/90bc8dd407d610201db8548c23431e942f759477/packages/hardhat/lib/tasks/forge/forgeTest.ts#L9). For now, there is a simple filename/block mapping in the task file, but we can extract this config somewhere else if we want as it grows. There are similar wrapper scripts defined in `package.json`: `yarn test:forge` in this package will invoke the Hardhat task and `yarn test:forge` at the project root will run it with Lerna.

This was the best out of a bunch of bad options I explored, but I think it will work for now. Switching fork blocks is coming Any Day Now to Foundry, but it's not quite ready.

2022-07-06 23:23 UTC, ecmendenhall commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    IERC20(vaultAsset).approve(address(zapperOut), feeBal);
We know here that `vaultAsset` is always a Curve LP token, right? Thinking about whether we need to zero approvals first or use `safeApprove`/`increaseAllowance`.

2022-07-06 23:23 UTC, ecmendenhall commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    uint256 amountOut = zapperIn.ZapIn{ value: msg.value }(
It's possible for the caller to provide native ETH accidentally even when they intend to do an ERC20 transfer. We should probably `require(msg.value == 0)` in the `if` statement above so that providing ETH + an ERC20 address reverts.

2022-07-06 23:23 UTC, ecmendenhall commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    uint256 withdrawn = IERC20(vaultAsset).balanceOf(address(this));
Should we use the same `balanceBefore`/`balanceAfter` pattern here?

2022-07-07 01:25 UTC, anthonymartin commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    IERC20(toToken).safeTransfer(_getContract(FEE_CONTROLLER_ID), amountOut);
even better!

2022-07-18 16:41 UTC, RedVeil commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +  function setFee(
Done

2022-07-18 16:42 UTC, RedVeil commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +  IZapIn constant zapperIn = IZapIn(0x5Ce9b49B7A1bE9f2c3DC2B2A5BaCEA56fa21FBeE);
I liked this to make it a little more explicit

2022-07-18 16:44 UTC, RedVeil commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    IERC20(vaultAsset).approve(address(zapperOut), feeBal);
i think we are good with that. In this zapper they have to be curve LP token. Otherwise we wouldnt be able to use these ZapIn and ZapOuts.

2022-07-25 15:57 UTC, ecmendenhall commented on packages/hardhat/contracts/core/defi/ZeroXZapper.sol
> +    _requireRole(DAO_ROLE);
```suggestion
  function removeVault(address underlyingToken) external onlyRole(DAO_ROLE) {
```

2022-08-22 11:27 UTC, merged

2022-08-22 11:27 UTC, anthonymartin approved these changes