Feature/keeper incentives updates
popcorndao/sweet-caramel pull request #723
Opened 2022-05-15 14:57 UTC by anthonymartin

2022-05-30 12:57 UTC, bhanusanghi requested changes
One Last comment - Should controllers have access to only incentives they are associated with? Currently no such check. We only check if the call handleKeeperIncentive is coming from a controller contract. 
This limits attack possibilities to only incentiveFunds associated with that controllerContract.

2022-05-30 12:57 UTC, bhanusanghi commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
>    uint256 public requiredKeeperStake;
Should KeeperStake be global or at Incentive level ? Since rewards vary with incentive, should stake vary too with incentive.

2022-05-30 12:57 UTC, bhanusanghi commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    rewardsTokensIncentiveAccounts[_rewardToken].push(incentiveAccountId);
When incentive is updated what happens to existing incentive Balance? It should be redirected to new incentiveAccountId.

2022-05-30 12:57 UTC, bhanusanghi commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    uint256 burnRate;
As it is not a function of time, should it be renamed to burnPercentage ?

2022-05-30 13:30 UTC, anthonymartin commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    uint256 burnRate;
true. good point

2022-06-07 01:06 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    burnBalance = _amount;
Should this increment `burnBalance` rather than setting it?

2022-06-07 01:06 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
>      burnRate = _burnRate;
Validate here too.

2022-08-04 18:14 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +  mapping(bytes32 => uint256) public lastPayouts;
now using lastInvocation in Incentive struct

2022-08-04 18:17 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    if (incentive.burnRate > 0) {
done

2022-08-04 18:17 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    burnAmount = (incentive.reward * incentive.burnRate) / 1e18;
done

2022-08-04 18:26 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +      _claim(incentiveAccountId, msg.sender);
done

2022-08-04 18:27 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    uint256 _burnRate
done

2022-08-04 18:28 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
> +    burnBalance = _amount;
done

2022-08-04 18:28 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
>      burnRate = _burnRate;
done

2022-08-04 18:33 UTC, anthonymartin commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
>    }
agreed - done

2022-08-04 18:33 UTC, anthonymartin commented on packages/hardhat/contracts/core/interfaces/IKeeperIncentiveV1.sol
> +interface IKeeperIncentive {
agreed - done

2022-08-04 18:51 UTC, anthonymartin commented on packages/hardhat/contracts/core/utils/KeeperIncentive.sol
>    address internal immutable burnAddress = 0x000000000000000000000000000000000000dEaD; // Burn Address
done

2022-08-04 19:35 UTC, anthonymartin commented on packages/hardhat/lib/adapters/KeeperIncentives/getKeeperAccounts.ts
> +import { KeeperIncentive } from "../../../typechain/KeeperIncentive";
@K-G-J i think we can delete this

2022-08-04 19:35 UTC, anthonymartin commented on packages/hardhat/lib/adapters/KeeperIncentives/getIncentiveBalance.ts
> +import { KeeperIncentive } from "../../../typechain/KeeperIncentive";
@K-G-J   i think we can delete this

2022-08-04 19:35 UTC, anthonymartin commented on packages/hardhat/test/__data__/KeeperIncentives/rewardsTokensIncentiveAccounts.json
> +[
@K-G-J i think we can delete this

2022-08-04 19:35 UTC, anthonymartin commented on packages/hardhat/test/__data__/KeeperIncentives/keeperIncentives.ts
> +export default [
@K-G-J i think we can delete this

2022-08-04 20:59 UTC, K-G-J commented on packages/hardhat/lib/adapters/KeeperIncentives/getKeeperAccounts.ts
> +import { KeeperIncentive } from "../../../typechain/KeeperIncentive";
agreed

2022-08-04 21:00 UTC, K-G-J commented on packages/hardhat/lib/adapters/KeeperIncentives/getIncentiveBalance.ts
> +import { KeeperIncentive } from "../../../typechain/KeeperIncentive";
agreed

2022-08-04 21:00 UTC, K-G-J commented on packages/hardhat/test/__data__/KeeperIncentives/rewardsTokensIncentiveAccounts.json
> +[
agreed

2022-08-04 21:00 UTC, K-G-J commented on packages/hardhat/test/__data__/KeeperIncentives/keeperIncentives.ts
> +export default [
agreed

2022-08-15 18:31 UTC, ecmendenhall reviewed
Leaving some first pass comments here! This is pretty much all style and nitpicks, I will give this another pass for the bigger stuff.

2022-08-15 18:31 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    }
Just a nitpick, let's put this check before the effects.

```suggestion
    if (!incentive.openToEveryone) {
      _requireRole(KEEPER_ROLE, _keeper);
    }
    
    incentives[msg.sender][_i].lastInvocation = block.timestamp;
```

2022-08-15 18:31 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +      block.timestamp - incentives[msg.sender][_i].lastInvocation >= incentive.cooldown,
You're reading this into memory on L#433 and can continue using it:

```suggestion
      block.timestamp - incentive.lastInvocation >= incentive.cooldown,
```

2022-08-15 18:31 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    _internalTransfer(_incentiveAccountId, address(this), address(0), amount);
Would it make sense to use `burnAddress` as the internal account for burned tokens as well?

2022-08-15 20:26 UTC, K-G-J commented on packages/hardhat/contracts/core/interfaces/IKeeperIncentiveV2.sol
> +bytes32 constant INCENTIVE_MANAGER_ROLE = 0x3bd2f1998541a778f2b17a84ff608b734af3ddf06cc43506453ef362dcdf17f1;
good to know!

2022-08-15 20:31 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    require(_cooldown > 0, "must set cooldown");
@anthonymartin I think @ecmendenhall has a good point here with making a cooldown lower than the average blocktime.  I was thinking we could make it 15 seconds since the average mainnet blocktime is 12 -14 seconds.

2022-08-15 21:14 UTC, K-G-J commented on packages/hardhat/contracts/core/interfaces/IKeeperIncentiveV2.sol
> +  function tip(
I think we should default to putting all our functions into our interfaces IMO

2022-08-16 15:19 UTC, ecmendenhall reviewed
Here comes round 2 :smile:

Left a few more comments here. Here is a checklist of some questions I asked and answered, and a few open questions.

**Answered questions:**
(But please check my work!)
- What prevents unauthorized callers from creating an incentive?
    - Creation is protected by ACLAuth and limited to the incentive manager role.
- What prevents unauthorized callers from claiming any incentive?
    - The caller must be an "allowed controller," added to the allowlist when the incentive is created
- Can attackers extract rewards through `claimFor`?
    - No, this always transfers the accrued balance to the keeper. An attacker can pass an invalid keeper address, but it will have a zero balance and revert.
- Do internal accounting invariants work as expected? (Zero transfers, self transfers)
    - Zero transfers are allowed (but change balances by zero)
    - Self transfers are allowed, accounting looks OK
    - Zero address is special-cased in internal transfers. Consider not doing this, so we can test internal invariants.
- What kind of tokens will this contract support?
    - We should avoid weird ERC20s like fee-on-transfer and rebasing tokens as keeper incentives, which could mess with internal accounting. For example, `tip` might transfer fewer tokens than expected if the tip token is a fee-on-transfer. `tip` is probably worse than `fundIncentive` because it will be called with smaller amounts more frequently. (USDT and USDC are both technically optional fee-on-transfer tokens, but it is pretty unlikely they ever turn these on). If we really want to be safe, we could follow a balance before/after pattern in `fundIncentive` and `tip`. 
    
**Questions/potential issues:**
- I see a potential griefing path through the `claimFor` mechanism. An external party can force a keeper to claim accrued rewards, even if unwanted by the keeper. The benefit of this is that someone else can cover the gas costs, but the downside is that it might have tax implications for the keeper. 
- There seems to be no mechanism to migrate deposited incentives in case of emergency or upgrade. What's the game plan if we ever need to replace the contract?
- What is the failure mode for dependent contracts if this one runs out of incentive tokens? Do calls to keeper incentivized functions revert? Can we better defend against failures here?
- A malicious admin could potentially set the burn percentage to 100% and burn all incentive. If we have a malicious admin, we have bigger problems, but it might be worth constraining this to build trust with keepers.

2022-08-16 15:19 UTC, ecmendenhall commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    toAccount.balance += to == address(0) ? 0 : amount;
It might be preferable to treat `address(0)` just like any other account here rather than special casing it. One benefit is that we could test the invariants here—the internal zero address balance should always be the sum of all tokens burned.

2022-08-16 18:34 UTC, ecmendenhall approved these changes

2022-08-16 18:34 UTC, ecmendenhall commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +    await setup();
Very much a nitpick, but I think the pattern we've adopted [in other tests](https://github.com/popcorndao/sweet-caramel/blob/df6f7c17d4876734c7bf7bdf82da94a238c1652c/packages/hardhat/test/ButterBatchProcessing.test.ts#L190) of returning the deployed contracts from the test `setup()` function is a good one to follow.

2022-08-16 18:34 UTC, ecmendenhall commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +      expect(false);
🤔 What's going on here? This just does nothing, right?

2022-08-16 18:34 UTC, ecmendenhall commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +      );
Ah, nice pattern here for structs. Maybe this deserves its own `expectStruct` helper.

2022-08-16 18:34 UTC, ecmendenhall commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +}
This looks like it would be useful as a separate helper.

2022-08-16 19:00 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    IERC20(incentive.rewardToken).safeTransferFrom(msg.sender, address(this), _amount);
I think this would be the preferred pattern to help protect against no ERC20 tokens getting transferred in or mismatches between _amount funded and the actual amount transferred @anthonymartin what do you think?

2022-08-16 19:06 UTC, K-G-J commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    toAccount.balance += to == address(0) ? 0 : amount;
I believe this is addressed by now sending burned tokens straight to the burn address balance in the update internal _burn function 
```solidity
  function _burn(
    uint256 amount,
    bytes32 _incentiveAccountId,
    address tokenAddress
  ) internal {
    burnBalancesByToken[tokenAddress] += amount;
    _internalTransfer(_incentiveAccountId, address(this), burnAddress, amount);
  }
```

2022-08-16 20:06 UTC, K-G-J commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +    await setup();
done 👍

2022-08-16 20:12 UTC, ecmendenhall commented
> We debated using the upgrading process from ButterBatchStorage, which still may possibly be implemented if deemed necessary. However, the current game plan uses two interfaces for keepers to claim their rewards. If we upgrade, we will allow keepers to claim all their rewards from the KeeperIncentivesV2 contract using one front-end and another front-end for them to claim their rewards with the new contract. Over time, if all tokens are claimed out of the previous KeeperIncentivesV2 contract, we will deactivate the claiming interface.

This all makes sense for claims. But isn't it possible for incentives to be overfunded? If someone has used `fundIncentive` to cover incentive payments that have not yet been earned by keepers, that amount would be lost, right?

2022-08-16 20:27 UTC, K-G-J commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +      expect(false);
good catch, removed the expect(false)

2022-08-16 21:19 UTC, K-G-J commented on packages/hardhat/test/KeeperIncentiveV2.test.ts
> +      );
good idea! We now have an expectStruct helper

2022-08-16 21:21 UTC, K-G-J commented
> > We debated using the upgrading process from ButterBatchStorage, which still may possibly be implemented if deemed necessary. However, the current game plan uses two interfaces for keepers to claim their rewards. If we upgrade, we will allow keepers to claim all their rewards from the KeeperIncentivesV2 contract using one front-end and another front-end for them to claim their rewards with the new contract. Over time, if all tokens are claimed out of the previous KeeperIncentivesV2 contract, we will deactivate the claiming interface.
> 
> This all makes sense for claims. But isn't it possible for incentives to be overfunded? If someone has used `fundIncentive` to cover incentive payments that have not yet been earned by keepers, that amount would be lost, right?

Yes so @anthonymartin and I discussed that incentive managers would need to know not to fund incentives for super long periods of time to avoid, but there is probably a better way to handle this. Let me think on it and try some things out.

2022-08-17 21:48 UTC, anthonymartin commented
> > > We debated using the upgrading process from ButterBatchStorage, which still may possibly be implemented if deemed necessary. However, the current game plan uses two interfaces for keepers to claim their rewards. If we upgrade, we will allow keepers to claim all their rewards from the KeeperIncentivesV2 contract using one front-end and another front-end for them to claim their rewards with the new contract. Over time, if all tokens are claimed out of the previous KeeperIncentivesV2 contract, we will deactivate the claiming interface.
> > 
> > 
> > This all makes sense for claims. But isn't it possible for incentives to be overfunded? If someone has used `fundIncentive` to cover incentive payments that have not yet been earned by keepers, that amount would be lost, right?
> 
> Yes so @anthonymartin and I discussed that incentive managers would need to know not to fund incentives for super long periods of time to avoid, but there is probably a better way to handle this. Let me think on it and try some things out.

Fund incentives wouldn't be used right away actually, so I don't think it's a big deal.

2022-08-17 23:23 UTC, anthonymartin commented on packages/hardhat/contracts/core/utils/KeeperIncentiveV2.sol
> +    IERC20(incentive.rewardToken).safeTransferFrom(msg.sender, address(this), _amount);
@K-G-J agreed

2022-08-18 14:17 UTC, RedVeil commented
@anthonymartin @K-G-J @ecmendenhall Logic looks sound to me. Its a lot simpler than before. But i would like to add some more empty lines in KeeperIncentiveV2 to group logic better and make it easier to read. Especially `tip` is quite the offender there.

2022-08-22 10:48 UTC, merged