Release/0.4.5
popcorndao/sweet-caramel pull request #744
Opened 2022-05-20 14:40 UTC by RedVeil

2022-05-24 15:39 UTC, anthonymartin requested changes

2022-05-24 15:39 UTC, anthonymartin commented on packages/app/helper/web3Onboard.tsx
>          token: "BSC",
shouldn't token be BNB?

2022-05-24 15:39 UTC, anthonymartin commented on packages/grants/components/Grants/GrantRound.tsx
> +          key={beneficiary.beneficiaryAddress.data}
we should not add `data`  like this to the interface. this will make the interfaces lightweight and simple. error and data handling should happen upstream and should leave the interface as it is

2022-05-24 15:39 UTC, anthonymartin commented on packages/grants/components/Grants/GrantRound.tsx
> +          key={beneficiary.beneficiaryAddress.data}
@Ajiva-D

2022-05-24 15:39 UTC, anthonymartin commented on packages/grants/components/Proposals/Form/BeneficiaryAddress.tsx
> +    setFormData({ ...formData.beneficiaryAddress, data });
this looks wrong. setFormData should be setting the entire form, but instead 2 strings are being saved as the form object @Ajiva-D

2022-05-25 08:21 UTC, RedVeil commented on packages/app/helper/web3Onboard.tsx
>          token: "BSC",
yes you are right. changed this

2022-05-25 08:22 UTC, RedVeil commented on packages/app/helper/ButterDataUtils.tsx
> +export async function getData(
Gotta say i liked the overloaded function. I did change the input interfaces though to extend a baseInput. that already cleans up a lot

2022-05-27 14:51 UTC, anthonymartin commented on .env.example
> +DEFAULT_CHAIN=ethereum
```suggestion
```

2022-06-01 14:36 UTC, anthonymartin approved these changes

2022-06-01 14:37 UTC, merged