exchanged img for next/Image
popcorndao/sweet-caramel pull request #981
Opened 2022-07-25 11:58 UTC by RedVeil

2022-07-25 12:01 UTC, anthonymartin requested changes
shouldn't the priority property be used for preloading images?

2022-07-25 12:01 UTC, anthonymartin commented on packages/app/components/BatchButter/SelectToken.tsx
> +  console.log(`/images/tokens/${selectedToken.img}`)
```suggestion
```

2022-07-25 12:26 UTC, RedVeil commented
> shouldn't the priority property be used for preloading images?

This is still super wip. It takes a little longer than expected to swap out img with nextImages. So currently im still swapping them out and making sure everything looks as expected. After that i check priority and placeholder images

2022-09-06 15:29 UTC, RedVeil commented
no longer applicable

2022-09-06 15:29 UTC, closed without merging